source/includes/_community.md
This addresses the discussion in #2
=> Add link to the new wiki page listing CDS services available for public testing and exploration

source/includes/_cds_services.md
Additionally, fixed a typo to show that the source is an object, not a string in the JSON. This address the issue noted in #19.
@robs16, @robcz, & @jmandel - is this change to all of your liking?
=> Clarify that a card's source is the primary source of guidance for the decision support

source/index.html.md
Add a notice indicating that CDS Hooks is still in development and soliciting feedback from users on a 1.0 release.
I'm adding this after @vadi2 mentioned to @jmandel & myself that when we first read the [CDS Hooks documentation](http://cds-hooks.org), he thought it was in much more a final state than it actually is. :-)
=> Add a notice indicating that CDS Hooks is still in development

source/includes/_cds_services.md
Switch from "name" to "title" in service discovery for consistency with
FHIR's use of name and title
=> Issue #40 - Switch from "name" to "title" in service discovery for consistency with FHIR's use of name and title

CODE_OF_CONDUCT.md, GOVERNANCE.md
This work is a joint collaboration between @jmandel, @isaacvetter, @brynrhodes, @mattberther, and myself. Thanks to many others who reviewed a draft of this proposed governance model and provided feedback.
As CDS Hooks matures as a community and standard, we feel it is important to formalize our governance process and establish a code of conduct. This will ensure that we all work in the same manner and have clear expectations for how we work.
Feedback and comments from everyone is welcome.
I will have an update for this pull request where both the governance and code of conduct are referenced in the homepage.
=> Add proposed governance and code of conduct document

source/includes/_cds_services.md
In discussion with @bdoolittle, @kendrapugh, @isaacvetter, @brynrhodes, and @jmandel we discussed that allowing users to choose at most one suggestion was preferable over our current approach of allowing a user to select as many suggestions as they want. Our reasoning is that choosing at most one suggestion prevents the user from choosing multiple suggestions that conflict or can cause patient harm.
=> Specify that users may choose at most one suggestion.

docs/specification/1.0.md, mkdocs.yml
This PR adds support for versioning the CDS Hooks specification. Today, the specification lives at `/specification`. With this change, it is now at `/specification/1.0`.
Future versioning can live at similar URLs. Eg:
- `/specification/1.1`
- `/specification/2.0`
This fixes #100
=> Add support for versioning the specification

docs/specification/1.0-api.yaml, docs/specification/1.0.md, mkdocs.yml
Merge the Open API Specification (Swagger) from the [cds-hooks/api](https://github.com/cds-hooks/api) repository into this repository.
Note that I've made this change on top of the specification versioning change to make it easier once that change gets merged in.
Fixes #117.
=> Add Open API Specification (Swagger)

docs/index.md, docs/specification/1.0-api.yaml, docs/specification/1.0.md
Remove decisions and the `redirect` parameter in preparation for a 1.0 release.
Fixes #99.
=> Remove decisions for the 1.0 release

docs/specification/1.0.md
Added clarification that the data elements a CDS service requests to be prefetched needs to be the "minimum necessary."  
Added priorities to CDS description table.  Responsive to risk #R16 from CDS service perspective.
Note that the table includes the statement "(todo: link to prefetching documentation)."  If this documentation does not exist, suggest deleting this statement.  Else add the link.
=> Document CDS Services should abide by accessing only the minimum necessary data neeeded

docs/specification/1.0.md
Incorporates all of the concepts we have discussed w.r.t. enabling an EHR to obtain a bearer token on behalf of a CDS service, and passing it on to that service in the service request.  I moved all of the pre-existing discussion re SMART into to introductory section so that the specification sections could be purely specification.  
I discovered that RFC7521 defines the "subject" parameter as "When using assertions as an authorization grant, the Subject identifies an authorized accessor for which the access token is being requested (typically, the resource owner or an authorized delegate)."  This seems to fit our purposes nicely, so I have used that as the identifier of the CDS Service that will be using the token.
=> Improve FHIR Resource Access documentation

docs/specification/1.0.md
This section was very hard to follow, especially w.r.t. what attributes were expansions of other attributes, etc.  The following changes were made:
1.  Moved the example to follow the field specifications (as we discussed).
2. Added "Priority" to all tables (except for the Card Attributes because Priorities were added by PR #131).  
3. Added sub-sections to show nesting of attributes.
4. Integrated "No Decision Support" content into "Card Array" section.
5. Integrated "Analytics" content into "Suggestion" section.
Question:  The Suggestion table references something called "Suggestion Tracking Analytics."  Is this a reference to the (moved) "Analytics" section, or to a separate resource?
=> CDS Service Response Changes

docs/specification/1.0.md
Modified example to align with parameters table by adding "fhirAuthorization" and "encounter" fields."  
Reworded description of "fhirAuthorization" parameter.
This change is responsive to Risk R7.
=> Minor edit to fhirAuthorization field documentation and example

docs/specification/1.0.md
1) Moved the example JSON to follow the specification
2) Added priorities to the HTTP request fields table.  NOTE:  We discussed the fact that aud should not be included in the fhirAuthorization structure because fhirServer was specified outside the fhirAuthorization structure.  However, a dependency exists between the two:  if fhirAuthorization is included, a fhirServer MUST be specified.  I've made them both OPTIONAL here, and noted that if fhirAuthorization is included, fhirServer is REQUIRED.  It might be cleaner to put fhirServer inside the fhirAuthorization structure so that fhirAuthorization could be OPTIONAL, but fhirServer (as a parameter of fhirAuthorization) could be REQUIRED.
=> Calling a CDS Service Mods

docs/specification/1.0.md
Because "context" is included in the HTTP call to invoke a CDS Service, developers will need to know its contents.  Added reference to the Hooks specification, where "context" is defined.
=> Add reference to Hooks page where context is described more fully

README.md, requirements.txt
- Uplift to the latest mkdocs-material and certifi
- Remove Gemnasium as this service is being EOL / shut down in a few months (see [this blog](https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/))
=> Update dependencies & remove Gemnasium

docs/specification/1.0.md
In addition to documenting that the JWK Set is communicated either via the standard `jku` header or out-of-band, I relaxed the `iss` value from URL to URI. This is to address deployment scenarios where the issuer cannot be a URL.
Fixes #87
=> Document how the JWK Set is communicated (fixes #87)

docs/specification/1.0.md
This includes the subset of HTML that GFM allows in its content. Fixes #319 and #355.
=> Use GitHub Flavored Markdown for the CDS card detail attribute as-is

docs/specification/1.0.md
Additionally, a reference to [rfc2818](https://tools.ietf.org/html/rfc2818) was added to fix #210
=> Clarify that the CDS Hooks APIs use TLS over HTTP (fixes #209 and #210)

docs/hooks/index.md
Organization-specific hooks SHALL use reverse domain name notation.
Fixes #335.
=> organization-specific hooks SHALL use reverse-DNS

docs/specification/1.0.md
Fixes #309 
I'm concerned that the hl7 url isn't stable yet. And we want links to work appropriately at both cds-hooks.org and cds-hooks.hl7.org.
I simply removed the link.
=> remove link to hooks section

docs/hooks/medication-prescribe.md, docs/hooks/order-review.md
Fixes #329 
I'm not updating the version of the hook, because I'm considering the completion of the HL7 ballot to be the beginning of 1.0. Also, this is a clarification, not necessarily a change.
=> Specify context resources are in draft status for the medication-prescribe and order-review hooks

docs/hooks/index.md
following version 1.x, the major version MAY be included in the name as "-2", "-3", etc. 
Fixes #291
=> Clarify the naming of subsequent major hook versions

docs/specification/1.0.md
Remove formal requirement level language from description of a process that is out of scope of the actual specification.
Fixes #268
=> Remove formal MUST language

docs/specification/1.0.md
Fixes #308.
The issue is that the link to FHIR's MedicationOrder resource no longer resolved. This is because from DSTU2->STU3, FHIR changed the name of this resource from MedicationOrder to MedicationRequest. Instead of pointing to the DSTU2 MedicationOrder resource, I updated the example and link to point to MedicationRequest.
=> link to MedRequest, not MedOrder

docs/specification/1.0.md
Additionally, the example JWT has been improved to include the public and private keys used to both sign and verify the signature.
This fixes #205
=> Add optional tenant JWT payload field (fixes #205)

docs/specification/1.0.md
=> Clarify when the CDS Service can leverage the FHIR server (fixes #247)

docs/specification/1.0.md
Fixes #410 
The `context.userId` field is (somewhat recently) defined to contains the FHIR resource name and identifier. For example, this field should contain: `Practitioner/123`. This was done to explicitly support scenarios other than provider-facing, for example, the user could be `Patient/456' or `Person/789` (following the [user-to-FHIR mapping](https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/148)) that SMART negotiated.
Because of this change, the prefetch example of `Practitioner/{{context.userId}}` would translate into `Practitioner/Practitioner/123` as issue #410 points out. 
This PR simply removes the "Practitioner/" string from the example, in lieu of the alternative, breaking changes suggested in #410.
=> Fix to prefetch example, for userId

docs/hooks/medication-prescribe.md, docs/hooks/order-review.md, docs/hooks/patient-view.md, mkdocs.yml
Fixes #445 
Other than the STU ballot, I think that `patient-view` is ready for CHMM5.
Maturity Level | Maturity title | Requirements
--- | --- | ---
4 | Documented | _The above, and …_ The author agrees that the artifact is sufficiently stable to require implementer consultation for subsequent non-backward compatible changes.  The hook is implemented in the standard CDS Hooks sandbox and multiple prototype projects. The Hook specification SHALL: <ul><ol>Identify a broad set of example contexts in which the hook may be used with a minimum of three, but as many as 8-10.</ol><ol>Clearly differentiate the hook from similar hooks or other standards to help an implementer determine if the hook is correct for their scenario.</ol><ol>Explicitly document example scenarios when the hook should not …
=> assign maturity to patient-view, med-prescribe, order-review

docs/community.md, docs/index.md, docs/quickstart.md, docs/specification/1.0.md
Fixes #407 
In general, use the term CDS Client instead of EHR. I mostly did a find & replace in the spec, but tried to be a bit more contextual in other places.
I specifically left the term EHR in the community.md, because I thought that was more accute.
Isaac
=> Change EHR to CDS Client (fixes #407)

docs/specification/1.0.md
Kudos to @hudsonma who identified this bad reference to the (now deleted, see #356) `sub` field while at the Connectathon today.
=> Remove reference to the deleted `sub` field

docs/hooks/medication-prescribe.md, docs/hooks/order-review.md, docs/hooks/order-select.md, docs/hooks/order-sign.md
Pull request to deprecate `medication-prescribe` and `order-review` hooks now that `order-select` and `order-sign` hooks have been created.
=> Deprecate medication-prescribe and order-review

docs/specification/1.0.md
This is a step toward satisfying trademark requirements, to show the logo on the official page where the spec is available. (Actually, I think it looks good too.)
=> Add logo to spec

cheat-sheet/cheat-sheet.md
Noticed that 'links' was mistakenly placed under 'suggestions'
=> Fix 'links' location in Cheat Sheet example

docs/specification/1.0.md
'sub' was removed from the JWT payload send to CDS Services with the following issue - https://github.com/cds-hooks/docs/issues/356
This PR removes it from a remaining example
=> Remove 'sub' from auth token JWT example

mkdocs.yml
We already have a deprecation notice on med-prescribe, but indicating so on the menu makes it more clear. 
Related to #433 and following the example set in PR #493.
=> better indicate that med-prescribe is deprecated

docs/specification/current.md
> A CDS Service MAY support a feedback endpoint; a CDS Client SHOULD be capable of sending feedback.
Fixes [FHIR-28683](https://jira.hl7.org/browse/FHIR-28683)
=> feedback, MAY for service, SHOULD for client

docs/specification/current.md
Fixes [FHIR-28688](https://jira.hl7.org/browse/FHIR-28688)
>"A comment entered by the clinician."
isntead of:
>"clinician entered comment"
=> minimal change to example override comment

docs/specification/current.md
except for the technical term "client identifier" and "client-side", remove all uses of the word client except when its capitalized and preceded by the term CDS, e.g. "CDS Client"
https://jira.hl7.org/browse/FHIR-28785
=> disambiguate term "client"

docs/examples.md
One of the json blocks did not properly close its backticks, so the following text blocks were being rendered as json.
=> fix formatting of json blocks in examples.md

.github/workflows/publish-docs.yml
We still want to keep cds-hooks.org up to date.
=> Reinstate cds-hooks.org publication

docs/quickstart.md
There was a link to the community page that wasn't prepended by a forward slash, so the browser made the link relative to the quickstart page instead of relative to the site.
=> Fix broken link in quickstart.md
