cds-hooks/docs

source/includes/_cds_services.md

Specify the response from CDS Services when no decision support is necessary

---

source/includes/_cds_services.md

Remove the 'success' indicator

---

docs/index.md

Just my first ever pull request - feel free to edit/tweak/discard.

minor edits to introduction section

---

docs/specification/1.0.md

Explicitly state that all data is sent/received as JSON (fixes #81)

Explicitly state that all data is sent/received as JSON (fixes #81).

---

docs/specification/1.0.md

Addresses [this comment](https://github.com/cds-hooks/docs/commit/b4b259101fde9fa1239ac94c7a527e20b5ac5748#r25932090) from @jmandel

Clarify the appContext documentation (see #59 and PR #112).

---

docs/specification/1.0.md

Proposing new section on Service Registration (to follow Discovery) that addresses risks and recommendations discussed in R2 and in today's discussion.

Add Service Registration section

---

docs/specification/1.0.md

This change addresses risk #R4.

Add documentation that all communication occur over TLS

---

docs/specification/1.0.md

Added priority field.  
Clarified that use of GitHub Flavored Markdown, without HTML, is required.  This addresses risk #R1.

Clarify Card attributes, including Priority

---

docs/specification/1.0.md

Added "Limitations" sub-section to "Overview."

Add new Limitations sections to document risks

---

docs/specification/1.0.md

Changes to clarify discovery of CDS services.  
Also to serve as the set-up for a new section on Service Registration -- to come.

Update Discovery documentation

---

docs/specification/1.0.md

Added explanation re RFC2119 standards terminology.

Reference RFC2119

---

docs/specification/1.0.md

Replaced most of this content with simple statement regarding CORS and a reference to the OWASP guidelines.

Cross-Origin Resource Sharing

---

docs/specification/1.0.md

Moved example JSON to follow specification.

Discovery Example

---

docs/specification/1.0.md

Pulled "Prefetch Template" and "FHIR Resource Access" into "Providing FHIR Resources to a CDS Service" section, as intended by PRs #132, #136, and #145.

Providing FHIR Resources convergence

---

docs/specification/1.0.md

Added Priorities to Card Array attributes table.

Card Array Attributes

---

docs/specification/1.0.md

remove todo, link to prefetch template section of spec.

Update prefetch section to remove TODO and mention risk of "stale" data (fixes #124)

---

requirements.txt

mkdocs: 0.17.2 -> 0.17.3
mkdocs-material: 2.6.2 -> 2.7.0

Update mkdocs and mkdocs-material theme dependencies.

---

docs/specification/1.0.md

Additionally, explicitly document that the public key is expressed as JWK in a JWK Set.
This fixes #152.

Add documentation regarding the JWT payload fields.

---

docs/hooks/index.md
docs/hooks/medication-prescribe.md
docs/hooks/order-review.md
docs/hooks/patient-view.md
docs/specification/1.0.md

#154: Initial draft of hook versioning support

---

docs/hooks/index.md
docs/hooks/order-review.md
docs/hooks/patient-view.md
docs/hooks/template.md
mkdocs.yml

#184: Added a hook definition template.

---

README.md
mkdocs.yml

The agreement between Boston Children's Hospital and HL7 requires joint copyright and the CC BY 4.0 license on the specification.
This is in line with the agreement made for SMART.

Add copyright and CC BY 4.0 license to the footer of each page.

---

docs/specification/1.0.md

Changed according to resolution.
Will fix #270

Require extensions to be JSON (fixes #270)

---

docs/specification/1.0.md

May 2018 Ballot Comment 150 #356
Removed sub field from the JWT payload

Remove sub field from the JWT payload (fixes #356)

---

docs/specification/1.0.md

Explain why the Open API Specification is supported (fixes #346)

---

docs/specification/1.0.md

Clarify the data stored alongside the access token in fhirAuthorization

---

docs/specification/1.0.md

Relax source.icon requirements and instead suggest the desired image format

---

docs/specification/1.0.md

Add links to the OAuth 2.0 homepage for reference (fixes #306)

---

docs/specification/1.0.md

Additional documentation around appContext

---

docs/specification/1.0.md

discovery endpoint shall include a description, not the purpose of the CDS service
Fixes #303

Minor update to Discovery documentation

---

docs/specification/1.0.md

Fixes #321 
Remove analytics until future release following implementer feedback.

remove analytics tracking

---

docs/quickstart.md

Fixes #297 
@brettmarquard - I'm only requesting your review on this one, 'cause it looks like you're actively reviewing this week, you wrote this content and it's a non-functional change to the spec.

spelling fix - add dash to "non secured"

---

docs/specification/1.0.md

Discovery endpoint & HTTP statuses

---

docs/specification/1.0.md

EHR MAY call discovery endpoint

---

docs/specification/1.0.md

update EHR access requirement (fixes #315)

---

docs/specification/1.0.md

update comment CDS Service attributes to SHALL (fixes #215)

---

docs/specification/1.0.md

add mandatory language to HTTP request

---

docs/specification/1.0.md

Update of may to MAY (resolves ballot comment 142)

---

docs/specification/1.0.md

removing use of pronoun 'we'

---

docs/specification/1.0.md

updated punctuation in tables

---

docs/specification/1.0.md

Minor clarification to the fhirAuthorization param (fixes #252)

---

docs/specification/1.0.md

Fixes #228: Added links to the FHIR specification for read and search interactions

---

docs/specification/1.0.md

Fixes #207: Added link to JWT RFC

---

docs/specification/1.0.md

Clarify pre-registration requirements of a CDS Service and AS

---

docs/specification/1.0.md

Document possible HTTP status codes a CDS Service may return (fixes #254)

---

docs/specification/1.0.md

Add brief summary of cards (fixes #351)

---

docs/specification/1.0.md

Remove limitations section as the content is duplicated further in the spec.

---

docs/specification/1.0.md

Add JWT alg standardization (fixes #187)

---

docs/specification/1.0.md

Clarify update actions contain full FHIR resources, not the diff

---

docs/specification/1.0.md

Recommend that hook authors name their context fields consistent with other hooks

---

docs/hooks/template.md
docs/specification/1.0.md

Require hook maturity level on hook definition

---

docs/hooks/appointment-book.md
docs/hooks/appointment-booking.md
mkdocs.yml

Proposed as part of the Davinci CRD project

Propose new appointment-book hook

---

docs/index.md

remove pre-1.0 language

---

docs/specification/current.md

Resolves: https://jira.hl7.org/browse/FHIR-28795
https://jira.hl7.org/browse/FHIR-28793
https://jira.hl7.org/browse/FHIR-28792

J#28795 spell out UUID, JSON and URL on first occurrence

---

docs/quickstart.md

JSON did not conform the CDS specification

typo in example JSON fragment

---

docs/specification/current.md

https://jira.hl7.org/browse/FHIR-28765

J#28765-format-json-better

---

docs/hooks/patient-view.md
docs/hooks/template.md
mkdocs.yml

https://jira.hl7.org/browse/FHIR-25758
Added a header to patient-view, as well as to the hook template.  Once we agree on wording, it can be propagated to other hook pages.

FHIR-25758 Add document context to patient-view

---

docs/hooks/patient-view.md

https://jira.hl7.org/browse/FHIR-25767 and FHIR-25761

FHIR-25767 Clarify userId input pattern on patient-view hook

---

docs/specification/current.md

fixes https://jira.hl7.org/browse/FHIR-28738 (why do you hate me, Dennis?)
I used https://jsonformatter.org/ with an indent of 2 tab space

standarize json indentation

---

docs/specification/current.md

fixes: https://jira.hl7.org/browse/FHIR-28695

even when not a JKU, key must be available

---

docs/specification/current.md

update example response to include overridesReasons

---

docs/specification/current.md

move security requirement to security section

---

docs/specification/current.md

Fixes [FHIR-28672](https://jira.hl7.org/browse/FHIR-28672)

improve example of missing prefetch data

---

docs/specification/current.md

Fixes [FHIR-28649](https://jira.hl7.org/browse/FHIR-28649)

serviceless CDS service should return an empty services array

---

docs/specification/current.md

Fixes [FHIR-28686](https://jira.hl7.org/browse/FHIR-28686) - adds mere headers

add headers to feedback examples

---

docs/specification/current.md

https://jira.hl7.org/browse/FHIR-28764
tested locally & everything!
Also:
* https://jira.hl7.org/browse/FHIR-28763
* https://jira.hl7.org/browse/FHIR-28754
all Josh's

I've got a fever, and the only prescription is more hyperlinks!

---

docs/specification/current.md

https://jira.hl7.org/browse/FHIR-28759

don't use word scope in non-technical way

---

docs/specification/current.md

Fixes https://jira.hl7.org/browse/FHIR-28753

correct misuse of term "FHIR identifier" to "FHIR id"

---

docs/specification/current.md

https://jira.hl7.org/browse/FHIR-28746
@dennispatterson - great catch on this.

formally define feedback uri and request structure

---

docs/specification/current.md

Fixes #509
and https://jira.hl7.org/browse/FHIR-28742
and https://jira.hl7.org/browse/FHIR-28741

selectionBehavior is CONDITIONAL; define CONDITIONAL

---

docs/specification/current.md

Fixes: https://jira.hl7.org/browse/FHIR-28717

help explain why service isn't informed of ignored cards

---

docs/specification/current.md

Fixes: https://jira.hl7.org/browse/FHIR-28702

clarify that CDS Service must be authorized to resources over REST

---

docs/hooks/order-dispatch.md
mkdocs.yml

As discussed on the CDS calls and as referenced in https://jira.hl7.org/browse/FHIR-34104

New order-dispatch hook proposal

---

docs/specification/current.md

Fixes https://jira.hl7.org/browse/FHIR-28714

reference card.indicator

---

docs/specification/current.md

Fixes: https://jira.hl7.org/browse/FHIR-28721

SHOULD revoke access token upon response

---

docs/specification/current.md

small wording enhancement, fixes: https://jira.hl7.org/browse/FHIR-28658

wording enhancement: CDS Service is subject to user authz

---

docs/best-practices.md
docs/specification/current.md

Fixes: https://jira.hl7.org/browse/FHIR-28720

auditing access to PHI is expected

---

docs/specification/current.md

fixes: https://jira.hl7.org/browse/FHIR-28698

recommend globally unique extension names

---

docs/specification/current.md

actions are transactions

---

docs/specification/current.md

Reverts cds-hooks/docs#610
Merged accidentally without feedback from Lloyd.

Revert "actions are transactions"

---

docs/specification/current.md

Addresses the resolution in [FHIR-28691.](https://jira.hl7.org/browse/FHIR-28691)
The comment "Given the current set of hooks, the CDS Hooks community should investigate hooks to support updates of the clinical record such as observations, medications, etc." is addressed in the Zulip stream : https://chat.fhir.org/#narrow/stream/179159-cds-hooks/topic/context-update.20hook

FHIR-28691 : update guidance

---

docs/specification/current.md

Erg. Recreating #610. Awaiting Lloyd's feedback for ... 2.5 weeks (week following DevDays, 22), at which point, I'll merge. 
Fixes FHIR-35878
Fixes https://github.com/cds-hooks/docs/issues/419

actions are transactions, recreated

---

docs/specification/current.md

per https://jira.hl7.org/browse/FHIR-28727

don't use patient in context as example

---

docs/hooks/appointment-book.md
docs/hooks/encounter-discharge.md
docs/hooks/order-select.md
docs/hooks/order-sign.md

Per https://confluence.hl7.org/display/CDS/CDS+Hooks+Hook+Maturity?flashId=653343941
and https://chat.fhir.org/#narrow/stream/179159-cds-hooks/topic/hook.20maturity.20--.20request.20for.20implementer.20feedback!

hook maturity level review

---

GOVERNANCE.md

Commiters are defined above PMC.

Fix ToC order in Governance

---

docs/hooks/appointment-book.md
docs/hooks/order-dispatch.md

fixes [FHIR-42146](https://jira.hl7.org/browse/FHIR-42146) and [FHIR-42140](https://jira.hl7.org/browse/FHIR-42140)

Some technical corrections per CDS Hooks Library ballot

---

docs/hooks/appointment-book.md
docs/hooks/medication-refill.md
docs/hooks/order-dispatch.md
mkdocs.yml

Should've been committed as 1, not zero

correct maturity of med-refill

---

docs/hooks/appointment-book.md

Added an admonition soliciting feedback, using exact language from [jira FHIR-42368.](https://jira.hl7.org/browse/FHIR-42368)

Solicit feedback per jira FHIR-42368

---

docs/hooks/encounter-start.md

Added an admonition soliciting feedback, using exact language from [jira FHIR-42369](https://jira.hl7.org/browse/FHIR-42369).

Solicit feedback per jira FHIR-42369

---

docs/hooks/order-dispatch.md

Changes reflect CDS WG discussion

Made order and task repeat, changed names.  

---

docs/hooks/order-sign.md

Removing generic statement per [jira FHIR-42367](https://jira.hl7.org/browse/FHIR-42367).

Remove generic statement per jira FHIR-42367

---

docs/hooks/order-dispatch.md

Per jira https://jira.hl7.org/browse/FHIR-42141, updating Task.code to reflect a more "real" example.

Add code and system to Task.code to reflect a more "real" example

---

docs/hooks/order-select.md

Fixes https://jira.hl7.org/browse/FHIR-42366

clean up order-select workflow description
